actors:
- name: whatever
  count: 1
  image: arrow.png
  width: 40
  height: 40
  speed: 4
  color:
    r: 255
    g: 0
    b: 0
    a: 255
  behaviors:
  # - type: BehaviorConstant
  #   data:
  #     direction:
  #     - 0.0
  #     - 1.0
  #     weight: 0.1
  - type: BehaviorKeyboard
    data:
      weight: 0.5   
  - type: BehaviorWander
    data:
      weight: 0.05
      changeInterval: 60   
window:
  height: 600
  title: AI Behaviors
  width: 800
