actors:
- name: leader
  count: 1
  image: arrow.png
  width: 30
  height: 30
  speed: 4
  color:
    r: 64
    g: 255
    b: 64
    a: 255
  behaviors:
  - type: constant
    data:
      direction:
      - 0.0
      - 1.0
      weight: 0.01
  - type: keyboard
    data:
      weight: 0.5   
  - type: wander
    data:
      weight: 0.05
      changeInterval: 60   
  - type: avoid
    data:
      weight: 0.2
      radius: 80.0
      target: "obstacle"
  - type: avoid
    data:
      weight: 0.2
      radius: 120.0
      target: "enemy"        
- name: drone
  count: 20
  image: arrow.png
  width: 30
  height: 30
  speed: 3
  color:
    r: 255
    g: 255
    b: 255
    a: 255
  behaviors:
  - type: wander
    data:
      weight: 0.03
      changeInterval: 15   
  - type: seek
    data:
      weight: 0.05
      target: "leader"   
  - type: avoid
    data:
      weight: 0.2
      radius: 80.0
      target: "obstacle"
  - type: avoid
    data:
      weight: 0.2
      radius: 120.0
      target: "enemy"  
- name: enemy
  count: 10
  image: arrow.png
  width: 30
  height: 30
  speed: 2
  color:
    r: 255
    g: 0
    b: 0
    a: 255
  position: #TODO allow setting specific position or random
  - 200.0
  - 150.0
  behaviors:
  - type: wander
    data:
      weight: 0.1
      changeInterval: 30   
  - type: seek
    data:
      weight: 0.1
      target: "leader"
  - type: avoid
    data:
      weight: 0.2
      radius: 80.0
      target: "obstacle"              
- name: obstacle
  count: 15
  image: warning.png
  width: 35
  height: 35
  speed: 0
  color:
    r: 255
    g: 255
    b: 0
    a: 255            
window:
  height: 600
  title: AI Behaviors
  width: 800
