actors:
- name: leader
  count: 1
  image: arrow.png
  width: 60
  height: 60
  speed: 2
  color:
    r: 150
    g: 255
    b: 255
    a: 255
  behaviors:
  - type: keyboard
    data:
      weight: 0.5   
  - type: wander
    data:
      weight: 0.05
      changeInterval: 240   
  - type: avoid
    data:
      weight: 0.2
      radius: 90.0
      target: obstacle1
  - type: avoid
    data:
      weight: 0.2
      radius: 90.0
      target: obstacle2   
  - type: avoid
    data:
      weight: 0.2
      radius: 90.0
      target: obstacle3 
  - type: avoid
    data:
      weight: 0.2
      radius: 90.0
      target: obstacle4              
  - type: avoid
    data:
      weight: 0.2
      radius: 120.0
      target: enemy        
- name: drone
  count: 10
  image: arrow.png
  width: 40
  height: 40
  speed: 1.2
  color:
    r: 255
    g: 255
    b: 150
    a: 255
  behaviors:
  - type: wander
    data:
      weight: 0.03
      changeInterval: 15   
  - type: seek
    data:
      weight: 0.05
      target: leader  
  - type: avoid
    data:
      weight: 0.2
      radius: 90.0
      target: obstacle1
  - type: avoid
    data:
      weight: 0.2
      radius: 90.0
      target: obstacle2   
  - type: avoid
    data:
      weight: 0.2
      radius: 90.0
      target: obstacle3 
  - type: avoid
    data:
      weight: 0.2
      radius: 90.0
      target: obstacle4   
  - type: avoid
    data:
      weight: 0.2
      radius: 120.0
      target: enemy  
- name: enemy
  count: 3
  image: arrow.png
  width: 40
  height: 40
  speed: 1
  color:
    r: 255
    g: 150
    b: 150
    a: 255
  behaviors:
  - type: wander
    data:
      weight: 0.1
      changeInterval: 30   
  - type: seek
    data:
      weight: 0.1
      target: leader
  - type: avoid
    data:
      weight: 0.2
      radius: 90.0
      target: obstacle1
  - type: avoid
    data:
      weight: 0.2
      radius: 90.0
      target: obstacle2   
  - type: avoid
    data:
      weight: 0.2
      radius: 90.0
      target: obstacle3 
  - type: avoid
    data:
      weight: 0.2
      radius: 90.0
      target: obstacle4          
- name: obstacle1
  count: 1
  image: warning.png
  width: 75
  height: 75
  speed: 0
  color:
    r: 205
    g: 205
    b: 0
    a: 255
  position:
    type: static
    data:
    - 200.0
    - 100.0      
- name: obstacle2
  count: 1
  image: warning.png
  width: 75
  height: 75
  speed: 0
  color:
    r: 205
    g: 205
    b: 0
    a: 255
  position:
    type: static
    data:
    - 600.0
    - 100.0     
- name: obstacle3
  count: 1
  image: warning.png
  width: 75
  height: 75
  speed: 0
  color:
    r: 205
    g: 205
    b: 0
    a: 255
  position:
    type: static
    data:
    - 200.0
    - 400.0      
- name: obstacle4
  count: 1
  image: warning.png
  width: 75
  height: 75
  speed: 0
  color:
    r: 205
    g: 205
    b: 0
    a: 255
  position:
    type: static
    data:
    - 600.0
    - 400.0              
window:
  height: 600
  title: AI Behaviors
  width: 800
  background:
    image: 
    color: 
      r: 155
      g: 155
      b: 155
      a: 255
      
