actors:    
- name: drone
  count: 300
  image: arrow.png
  width: 20
  height: 20
  speed: 2
  color:
    r: 255
    g: 255
    b: 150
    a: 255
  behaviors:
  - type: wander
    data:
      weight: 0.03
      changeInterval: 120   
  - type: avoid
    data:
      weight: 0.2
      radius: 120.0
      target: enemy        
- name: enemy
  count: 3
  image: arrow.png
  width: 30
  height: 30
  speed: 1
  color:
    r: 255
    g: 150
    b: 150
    a: 255
  behaviors:
  - type: wander
    data:
      weight: 0.1
      changeInterval: 120   
window:
  height: 600
  title: AI Behaviors
  width: 800
  background:
    image: 
    color: 
      r: 125
      g: 125
      b: 125
      a: 255
      
